apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-stream-processor
  namespace: default
  labels:
    app: risk-stream-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk-stream-processor
  template:
    metadata:
      labels:
        app: risk-stream-processor
    spec:
      containers:
      - name: risk-stream-processor
        image: 480609332059.dkr.ecr.ap-southeast-1.amazonaws.com/risk-stream-processor:latest
        imagePullPolicy: Always
        command: ["java", "-Dlog4j2.configurationFile=/etc/config/log4j2.properties", "-jar", "app.jar"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        env:
        - name: KAFKA_BROKERS
          value: "kafka-cluster.kafka.svc:9092"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: config-volume
        configMap:
          name: risk-logging-config
