status: in-progress
root: true
name: log4j2-root-config

appenders:
  console:
    type: Console
    name: STDOUT
    layout:
      type: PatternLayout
      pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n"

loggers:
  root:
    level: info
    appenderRef:
      ref: STDOUT
