apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "risk-calculator-service.fullname" . }}
  labels:
    {{- include "risk-calculator-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "risk-calculator-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "risk-calculator-service.selectorLabels" . | nindent 8 }}
        app: {{ include "risk-calculator-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.bootstrapServers | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
