replicaCount: 1

image:
  repository: 480609332059.dkr.ecr.ap-southeast-1.amazonaws.com/ingestion-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

env:
  simulatorHost: "market-data-simulator"
  simulatorPort: "9999"
  kafkaBootstrapServers: "kafka-cluster.kafka:9092"
  kafkaTopic: "market.raw.prices"
  retryInterval: "5"
  dbHost: "timescaledb.timescaledb.svc.cluster.local"
  dbPort: "5432"
  dbName: "postgres"
  dbUser: "postgres"
  dbPass: "timescale_password"

resources:
  limits:
    cpu: 500m
    memory: 384Mi
  requests:
    cpu: 100m
    memory: 128Mi
