apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "risk-stream-processor.fullname" . }}
  labels:
    {{- include "risk-stream-processor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "risk-stream-processor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "risk-stream-processor.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "risk-stream-processor.fullname" .) }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BROKERS
              value: {{ .Values.env.kafkaBrokers | quote }}
            - name: APPLICATION_ID
              value: {{ .Values.env.appId | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
