apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "risk-stream-processor.fullname" . }}
  labels:
    {{- include "risk-stream-processor.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "risk-stream-processor.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "risk-stream-processor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "risk-stream-processor.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "risk-stream-processor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["java", "-Dlog4j2.configurationFile=/etc/config/log4j2.properties", "-jar", "app.jar"]
          env:
            - name: KAFKA_BROKERS
              value: {{ .Values.env.kafkaBrokers | quote }}
            - name: APPLICATION_ID
              value: {{ .Values.env.appId | quote }}
            - name: KAFKA_STREAMS_STATE_DIR
              value: {{ .Values.persistence.mountPath | quote }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            {{- if .Values.persistence.enabled }}
            - name: rocksdb-data
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: risk-logging-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: rocksdb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.persistence.storageClass | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
  {{- end }}
