replicaCount: 1

image:
  repository: 480609332059.dkr.ecr.ap-southeast-1.amazonaws.com/risk-stream-processor
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: false
  name: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

env:
  kafkaBrokers: "kafka-cluster.kafka.svc:9092"
  appId: "risk-stream-processor"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

persistence:
  enabled: true
  storageClass: "gp2"
  size: 10Gi
  mountPath: "/tmp/kafka-streams"

